### ISSUE TITLE
PCLCrypto cannot be used in a .NET Core project?

### ISSUE THREAD

**Issue by adonisv79** [AArnott/PCLCrypto#132] opened 2017-06-21 05:35 UTC
Good day sir, I was going t use PCLCrypto on a newly created ".NET Core" console application. however adding the latest version from nuget results in an error.

STeps: 
1. in visual studio, creat a new .NET core console application
2. in dependencies, select Nuget and search for PCLCrypto
3. click install
--------------------------------------------------------------
Result:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Package restore failed. Rolling back package changes for 'ConsoleApp1'.			0	

---------------------------------------------------------------
Running restore with 8 concurrent jobs.
Reading project file c:\users\adonis villamor\Documents\visual studio 2015\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj.
Restoring packages for c:\users\adonis villamor\Documents\visual studio 2015\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj...
Restoring packages for .NETCoreApp,Version=v1.1...
Resolving conflicts for .NETCoreApp,Version=v1.1...
Checking compatibility of packages on .NETCoreApp,Version=v1.1.
Checking compatibility for ConsoleApp1 1.0.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for PCLCrypto 2.0.147 with .NETCoreApp,Version=v1.1.
**Package PCLCrypto 2.0.147 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package PCLCrypto 2.0.147 supports:
  - monoandroid23 (MonoAndroid,Version=v2.3)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32)
  - wp8 (WindowsPhone,Version=v8.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)**
Checking compatibility for Microsoft.NETCore.App 1.1.2 with .NETCoreApp,Version=v1.1.
Checking compatibility for Validation 2.2.8 with .NETCoreApp,Version=v1.1.
**Package Validation 2.2.8 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Validation 2.2.8 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - portable-dnxcore50+monoandroid10+monotouch10+net45+win+wp8+wpa81+xamarinios10 (.NETPortable,Version=v0.0,Profile=net45+dnxcore50+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)**
Checking compatibility for PInvoke.NCrypt 0.3.2 with .NETCoreApp,Version=v1.1.
**Package PInvoke.NCrypt 0.3.2 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package PInvoke.NCrypt 0.3.2 supports:
  - net40 (.NETFramework,Version=v4.0)
  - portable-net40+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile92)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)**
Checking compatibility for Libuv 1.9.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.CodeAnalysis.CSharp 1.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.CodeAnalysis.VisualBasic 1.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.CSharp 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.DiaSymReader.Native 1.4.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.NETCore.DotNetHostPolicy 1.1.2 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.NETCore.Runtime.CoreCLR 1.1.2 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.VisualBasic 10.1.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for NETStandard.Library 1.6.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Buffers 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Collections.Immutable 1.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.ComponentModel 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.ComponentModel.Annotations 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Diagnostics.DiagnosticSource 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Diagnostics.Process 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Dynamic.Runtime 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Globalization.Extensions 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.IO.FileSystem.Watcher 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.IO.MemoryMappedFiles 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.IO.UnmanagedMemoryStream 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Linq.Expressions 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Linq.Parallel 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Linq.Queryable 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Net.Http 4.3.2 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Net.NameResolution 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Net.Requests 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Net.Security 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Net.WebHeaderCollection 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Numerics.Vectors 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection.DispatchProxy 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection.Metadata 1.4.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection.TypeExtensions 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Resources.Reader 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Runtime.Loader 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Cryptography.Algorithms 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Cryptography.Encoding 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Cryptography.Primitives 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Cryptography.X509Certificates 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading.Tasks.Dataflow 4.7.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading.Tasks.Extensions 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading.Tasks.Parallel 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading.Thread 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading.ThreadPool 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.CodeAnalysis.Common 1.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Collections 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Diagnostics.Debug 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Globalization 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Linq 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.ObjectModel 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection.Extensions 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection.Primitives 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Resources.ResourceManager 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Runtime 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Runtime.Extensions 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Runtime.InteropServices 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.NETCore.DotNetHostResolver 1.1.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.NETCore.Jit 1.1.2 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.NETCore.Windows.ApiSets 1.0.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.NETCore.Platforms 1.1.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.Win32.Primitives 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.AppContext 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Collections.Concurrent 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Console 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Diagnostics.Tools 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Diagnostics.Tracing 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Globalization.Calendars 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.IO 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.IO.Compression 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.IO.Compression.ZipFile 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.IO.FileSystem 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.IO.FileSystem.Primitives 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Net.Primitives 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Net.Sockets 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Runtime.Handles 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Runtime.InteropServices.RuntimeInformation 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Runtime.Numerics 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Text.Encoding 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Text.Encoding.Extensions 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Text.RegularExpressions 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading.Tasks 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading.Timer 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Xml.ReaderWriter 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Xml.XDocument 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.Win32.Registry 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.native.System 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection.Emit 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection.Emit.ILGeneration 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Threading.Overlapped 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Reflection.Emit.Lightweight 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.native.System.Net.Http 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Cryptography.OpenSsl 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Principal.Windows 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.native.System.Net.Security 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Claims 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Principal 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.native.System.Security.Cryptography.Apple 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Cryptography.Cng 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Security.Cryptography.Csp 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.CodeAnalysis.Analyzers 1.1.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Diagnostics.FileVersionInfo 4.0.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Diagnostics.StackTrace 4.0.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Text.Encoding.CodePages 4.0.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Xml.XmlDocument 4.0.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Xml.XPath.XDocument 4.0.1 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.NETCore.Targets 1.1.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for Microsoft.NETCore.DotNetHost 1.1.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.native.System.IO.Compression 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.0 with .NETCoreApp,Version=v1.1.
Checking compatibility for System.Xml.XPath 4.0.1 with .NETCoreApp,Version=v1.1.
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Incompatible packages: 3
Package restore failed. Rolling back package changes for 'ConsoleApp1'.
Time Elapsed: 00:00:00.4653560
========== Finished ==========

**Comment by AArnott** [comment] 2017-06-21 19:24
Dupe of #103

**Closed by AArnott** 2017-06-21 19:24 UTC
