### ISSUE TITLE
Using SymmetricKeyAlgorithmProvider in PCL codebase ios

### ISSUE THREAD

**Issue by pricimus** [AArnott/PCLCrypto#10] opened 2015-02-10 17:52 UTC
Hi,

I have the following method:

            public string Encrypt(string stringToEncrypt, string cryptoKey)
		{
			byte[] keyMaterial = System.Text.Encoding.UTF8.GetBytes (cryptoKey);
			byte[] data = System.Text.Encoding.UTF8.GetBytes (stringToEncrypt);
			var provider =          WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
			var key = provider.CreateSymmetricKey (keyMaterial);
			byte[] cipherText = WinRTCrypto.CryptographicEngine.Encrypt(key, data);

			return Convert.ToBase64String (cipherText);
		}

The line var provider =          WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7); fails with error System.NotImplementedException: Not implemented in reference assembly

I'm confused as I thought the point of the library was to provide cryptographic support for codebases that use the PCL. Is SymmetricKeyAlgorithmProvider not available to PCL codebases? And if not, what is the way to encrypt/decrypt strings on iOS devices?

**Comment by AArnott** [comment] 2015-02-10 18:38
Dupe of this http://pclcrypto.codeplex.com/discussions/570690#post1347663

**Closed by AArnott** 2015-02-10 18:38 UTC

**Comment by pricimus** [comment] 2015-02-10 21:32
That's not solved it unfortunately.
