### ISSUE TITLE
Breaking change of Xamarin.iOS 9 (NSMutableDictionary) - application no longer compiles

### ISSUE THREAD

**Issue by PaulAchess** [AArnott/PCLCrypto#42] opened 2015-10-27 15:57 UTC
Hi,

I just installed the new Xamarin.iOS version and a breaking change is causing us trouble. On compilation, we have the following error: `Failed to resolve System.Void MonoTouch.Foundation.NSMutableDictionary`.

This is due to a breaking changing in Xamarin.iOS 9 regarding NSMutableDictionary : https://developer.xamarin.com/releases/ios/xamarin.ios_9/xamarin.ios_9.0/

They are now generic-based.

We can see the use of NSMutableDictionary here for instance : https://github.com/AArnott/PCLCrypto/blob/master/src/PCLCrypto.Shared.iOS/RsaAsymmetricKeyAlgorithmProvider.cs
But also in several other files.

Maybe a simple recompile would be enough.

Hoping this helps, I also use this occasion to tell you that your library is awesome :)

PS: we thought this bug was coming from Xamarin, the discussion is here (https://bugzilla.xamarin.com/show_bug.cgi?id=34621)

**Comment by rolfbjarne** [comment] 2015-10-27 16:12
(Xamarin employee here)

The fix is to recompile any Xamarin.iOS libraries with Xamarin.iOS 9.0.1, no code changes are required.

**Comment by AArnott** [comment] 2015-10-27 17:33
Thanks for the report. And thanks @rolfbjarne for the tip. I need to support older versions as well, so I guess I need to fork my Xamarion.iOS project so I can compile against both API versions, correct? Which exact version is the first with the change?
And in NuGet packaging, what do I use as the TxM folder to discern Xamarin.iOS 9.0.1 (if that's the particular version) from earlier versions so I can package up both?

**Comment by bholmes** [comment] 2015-10-27 19:03
@AArnott,  

@rolfbjarne would know best but I know he is busy so I will take a stab at this.

The API change in question only occurred in the early Xamarin.iOS 9.0 series.  It is my understanding that the new call that was introduced caused an error and would not work.  That is why it had to be removed.  There should be no API change between pre 9.0 and the latest 9.0 install.  

I do not believe that you have to be concerned with building for the early 9.0 builds that had the new call that was later removed.

-Bill

**Comment by bholmes** [comment] 2015-10-27 19:39
@AArnott  please hold off on the rebuild if you are using VS.  I suspect that you are.

**Comment by AArnott** [comment] 2015-10-27 21:01
yes @bholmes, I'm using VS. What am I waiting for?

I agree if 9.0.0 was broken and that before and after that version it worked, I can make sure to not compile PCLCrypto with 9.0.0. How do I know what version I'm compiling with?

**Comment by rolfbjarne** [comment] 2015-10-27 21:06
The problem only occurs if you build with Xamarin.iOS 9.0.0.

We introduced a broken indexer overload in 9.0.0, and due to C# overloading resolution rules, existing code would call the broken indexer overload (if built with Xamarin.iOS 9.0.0). The fix we did for 9.0.1 was to remove the broken indexer overload, which will cause all usages of the indexer to resolve to the old (and working) overload.

This means that there's no reason to build multiple versions of your library.

**Comment by AArnott** [comment] 2015-10-27 22:05
Understood, @rolfbjarne. Thank you.
How do I know whether I'm compiling against 9.0.0?

**Comment by bholmes** [comment] 2015-10-27 22:27
@AArnott you are waiting for a VS build that has this fix.  I found out earlier today that the API fix did not hit that product.  What you are looking for is NSMutableDictionary to NOT have a `this[INativeObject]` overload.  You can check this in your assembly browser. 

http://screencast.com/t/TFgQgUM0C   - this is a snaphot of my broken image.

I believe the fix is in our Beta channel but I have not confirmed.  Also that Beta build will be promoted to stable soon.  I am thinking that you want to wait for that release.  I will update you here as I learn more.

I did not want you to republish the same error.

**Comment by awaisali88** [comment] 2015-10-29 06:49
Hi i am using PCLCrypto library in my xamarin forms project. Everything else is working fine and i am stuck in building the iOS project because of this bug. Can you please fix it as soon as possible.

**Comment by PaulAchess** [comment] 2015-10-29 10:11
You have a workaround in the comment 47 of this Xamarin Bugzilla discussion : https://bugzilla.xamarin.com/show_bug.cgi?id=34621

**Comment by awaisali88** [comment] 2015-10-29 11:09
Let me check this.
Thanks

**Comment by bholmes** [comment] 2015-10-29 14:24
@AArnott I see that the build new build is available in the stable channel.  I believe that if you rebuild with the latest the issue will be resolved.  

Here is a screenshot of the INativeObject overload removed and the version is the about dialog box.

http://screencast.com/t/4VDvveX7Vtg

Thanks for you help!

**Comment by alexrainman** [comment] 2015-11-02 17:05
@AArnott same issue here:

```
key = asym.CreateKeyPair(512);
```

throws this exception: Method 'NSMutableDictionary.set_Item' not found.

**Comment by AArnott** [comment] 2015-11-05 15:57
I have confirmed that a recompile changes the NSDictionary.set_Item that is called. I'm preparing to ship a new build.

**Closed** 2015-11-05 16:01 UTC
Labels: bug

**Comment by AArnott** [comment] 2015-11-05 16:06
1.0.82 has been pushed to nuget.org
