### ISSUE TITLE
Linking failed with latest nuget  in Xamarin project

### ISSUE THREAD

**Issue by AlexanderOsokin** [AArnott/PCLCrypto#86] opened 2016-04-01 11:56 UTC
Reference to metadata item 'System.Runtime.InteropServices.ComTypes.FILETIME' (defined in 'PInvoke.Kernel32, Version=0.2.0.0, Culture=neutral, PublicKeyToken=9e300f9f87f04a7a') from 'PInvoke.Kernel32, Version=0.2.0.0, Culture=neutral, PublicKeyToken=9e300f9f87f04a7a' could not be resolved.

**Comment by AArnott** [comment] 2016-04-01 14:13
Dupe of #85

**Closed by AArnott** 2016-04-01 14:13 UTC
