### ISSUE TITLE
Please update MinClient Version

### ISSUE THREAD

**Issue by jamesmontemagno** [AArnott/PCLCrypto#16] opened 2015-03-25 17:17 UTC
<metadata minClientVersion="2.8.3"> 

this causes an issue in Xamarin studio, which is only 2.8.1, can you please update this.

**Comment by AArnott** [comment] 2015-03-25 17:18
Dupe of #13

**Closed by AArnott** 2015-03-25 17:18 UTC

**Comment by jamesmontemagno** [comment] 2015-03-25 17:20
Can you update it to 2.8.1?

**Comment by AArnott** [comment] 2015-03-25 17:59
Let's focus the discussion in #13
